name: guardiancare
description: "A Educational App."

publish_to: 'none'

version: 1.0.0+16

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.0
  flutter_gemini: ^3.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.7
  get: ^4.7.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.1.0
  firebase_auth: ^5.3.5
  firebase_core: ^3.9.0
  sign_in_button: ^4.0.1
  youtube_parser: ^2.1.3
  http: ^1.5.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  flutter_email_sender: ^6.0.3
  shimmer: ^3.0.0
  cloud_firestore: ^5.6.0
  youtube_player_flutter: ^9.1.3
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^6.2.2
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  flutter_inappwebview: ^6.1.5
  email_validator: ^3.0.0
  pdfx: ^2.9.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  injectable: ^2.3.2
  crypto: ^3.0.7
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^3.0.3
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  injectable_generator: ^2.4.1

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  color_dark: "#ffffff"
  image: "assets/logo/logo_splash.png"
  image_dark: "assets/logo/logo_splash.png"
  android_gravity: "center"

  android_12:
    image: assets/logo/logo_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/logo_splash.png
    icon_background_color_dark: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo.png"
