name: guardiancare
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  sign_in_button: ^3.2.0
  youtube_parser: ^2.1.3
  http: ^0.13.5
  webview_flutter: ^2.0.13 # Add webview_flutter dependency
  url_launcher: ^6.2.5
  flutter_email_sender: ^6.0.2
  shimmer: ^3.0.0
  cloud_firestore: ^4.15.9
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
